production:
  small_worker:
    class: SmallWorkerJob
    queue: default
    schedule: "every 30 minutes"

development:
  small_worker:
    class: SmallWorkerJob
    queue: default
    schedule: "every 30 minutes"
