require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Surface SMTP failures during development so mail issues are visible.
  config.action_mailer.raise_delivery_errors = ENV.fetch("MAILER_RAISE_DELIVERY_ERRORS", "true") == "true"

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # SMTP settings for sending emails.
  config.action_mailer.delivery_method = :smtp
  smtp_settings = {
    address: ENV.fetch("SMTP_ADDRESS", "localhost"),
    port: ENV.fetch("SMTP_PORT", 1025).to_i,
    domain: ENV.fetch("SMTP_DOMAIN", "localhost"),
    enable_starttls_auto: ENV.fetch("SMTP_ENABLE_STARTTLS", "false") == "true"
  }
  # Some providers require POP-before-SMTP in addition to SMTP AUTH.
  if ENV["SMTP_USERNAME"].present?
    smtp_settings[:user_name] = ENV["SMTP_USERNAME"]
    smtp_settings[:password] = ENV["SMTP_PASSWORD"]
    smtp_settings[:authentication] = :plain
  end
  config.action_mailer.smtp_settings = smtp_settings
  config.action_mailer.perform_deliveries = true

  config.after_initialize do
    masked_user = if ENV["SMTP_USERNAME"].present?
      "#{ENV['SMTP_USERNAME'][0, 2]}***"
    end

    Rails.logger.info(
      "[ActionMailer] SMTP settings " \
      "address=#{smtp_settings[:address]} " \
      "port=#{smtp_settings[:port]} " \
      "domain=#{smtp_settings[:domain]} " \
      "starttls=#{smtp_settings[:enable_starttls_auto]} " \
      "user=#{masked_user || '(none)'} " \
      "pop_before_smtp=#{ENV['POP_ADDRESS'].present?}"
    )
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Allow all hosts in development.
  config.hosts.clear

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  config.generators do |g|
    g.test_framework :rspec,
                     fixtures: false,
                     view_specs: false,
                     helper_specs: false,
                     routing_specs: false,
                     controller_specs: false,
                     request_specs: false
  end
end
